Q1) Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)

In [1]:
# importing pandas, numpy and Dataset
import pandas as pd
import numpy as np
Liga = pd.read_csv("Laliga.csv")

In [2]:
Liga.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1

In [3]:
# Making first row as index
Liga = Liga.rename(columns=Liga.iloc[0]).drop(Liga.index[0])

In [4]:
# Checking if Pos is unique or not
Liga['Pos'].is_unique

True

In [5]:
# Making Pos column as index
Liga = Liga.set_index('Pos')

In [6]:
# Replacing - with 0 for better arithmetic operations
Liga = Liga.replace('-',0)
Liga.head(10)

,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
Pos,,,,,,,,,,,,,,,,,,,
1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
7,Espanyol,82,2792,2626,948,608,1070,3609,3889,0,0,4,5,2,5,16,1929,1994-95,3
8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939-40,2012-13,2
10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932-33,2015-16,1

Q2) Print all the teams which have started playing between 1930-1980. (5 points)

In [7]:
#Converting Debut & Since/LastApp columns to int type by removing -## from the data
extr = Liga['Debut'].str.extract(r'^(\d{4})', expand=False)

In [8]:
Liga['Debut'] = pd.to_numeric(extr)

In [9]:
extr1 = Liga['Since/LastApp'].str.extract(r'^(\d{4})', expand=False)
Liga['Since/LastApp'] = pd.to_numeric(extr1)

In [10]:
Liga.dtypes

Team             object
Seasons          object
Points           object
GamesPlayed      object
GamesWon         object
GamesDrawn       object
GamesLost        object
GoalsFor         object
GoalsAgainst     object
Champion         object
Runner-up        object
Third            object
Fourth           object
Fifth            object
Sixth            object
T                object
Debut             int64
Since/LastApp     int64
BestPosition     object
dtype: object

In [11]:
#Applying Condition
df = Liga.loc[(Liga["Debut"] >= 1930) & (Liga["Debut"] <= 1980)]

In [12]:
#The teams which have started playing between 1930-1980 are : 
df["Team"]

Pos
4                Valencia
6                 Sevilla
9                Zaragoza
10             Real Betis
11    Deportivo La Coruna
12             Celta Vigo
13             Valladolid
15         Sporting Gijon
16                Osasuna
17                 Malaga
18                 Oviedo
19               Mallorca
20             Las Palmas
22                Granada
23         Rayo Vallecano
24                  Elche
26               Hercules
27               Tenerife
28                 Murcia
29                 Alaves
30                Levante
31              Salamanca
32               Sabadell
33                  Cadiz
35              Castellon
38                Cordoba
40             Recreativo
41              Burgos CF
42             Pontevedra
47              Gimnastic
50               Alcoyano
51                   Jaen
53             AD Almeria
55                 Lleida
58                 Condal
59        Atletico Tetuan
60       Cultural Leonesa
Name: Team, dtype: object

Q3) Print the list of teams which came Top 5 in terms of points (2.5 points)

In [13]:
#Since by now all the null values are replaced by 0, all the columns can be converted to int
Liga = Liga.convert_objects(convert_numeric=True)

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [14]:
Liga.sort_values(by=["Points"],ascending=False).head(5)

,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
Pos,,,,,,,,,,,,,,,,,,,
1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002,1
4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987,1
5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

Q4) Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. (5 points)
Goal_diff_count = GoalsFor - GoalsAgainst

In [15]:
Liga["Goal_diff_count"] = Liga["GoalsFor"] - Liga["GoalsAgainst"]

In [16]:
Liga.loc[:,["Team","Goal_diff_count"]]

                    Team  Goal_diff_count
Pos
1            Real Madrid             2807
2              Barcelona             2786
3        Atletico Madrid             1225
4               Valencia              929
5        Athletic Bilbao              931
6                Sevilla              307
7               Espanyol             -280
8          Real Sociedad               -2
9               Zaragoza             -164
10            Real Betis             -333
11   Deportivo La Coruna             -136
12            Celta Vigo             -346
13            Valladolid             -413
14      Racing Santander             -525
15        Sporting Gijon             -399
16               Osasuna             -334
17                Malaga             -342
18                Oviedo             -309
19              Mallorca             -189
20            Las Palmas             -399
21            Villarreal              103
22               Granada             -338
23        Rayo Vallecano             -328
24                 Elche             -272
25                Getafe             -113
26              Hercules             -334
27              Tenerife             -125
28                Murcia             -385
29                Alaves             -165
30               Levante             -202
..                   ...              ...
32              Sabadell             -228
33                 Cadiz             -269
34              Logrones             -198
35             Castellon             -169
36              Albacete              -90
37               Almeria             -122
38               Cordoba             -145
39            Compostela              -42
40            Recreativo              -94
41             Burgos CF              -94
42            Pontevedra              -56
43              Numancia              -98
44                 Eibar              -28
45                Arenas              -81
46           Real Burgos              -38
47             Gimnastic             -114
48           Extremadura              -55
49                Merida              -45
50              Alcoyano             -107
51                  Jaen              -62
52            Real Union              -31
53            AD Almeria              -45
54                Europa              -34
55                Lleida             -112
56               Leganes              -19
57                 Xerez              -28
58                Condal              -20
59       Atletico Tetuan              -34
60      Cultural Leonesa              -31
61                Girona                0

[61 rows x 2 columns]

In [17]:
Liga = Liga.sort_values(by=["Goal_diff_count"],ascending=False)

In [18]:
Liga.head(15)

,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Goal_diff_count
Pos,,,,,,,,,,,,,,,,,,,,
1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1,2807
2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1,2786
3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002,1,1225
5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1,931
4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987,1,929
6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934,2001,1,307
21,Villarreal,17,970,646,266,172,208,892,789,0,1,1,2,3,2,9,1998,2013,2,103
61,Girona,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2017,2017,9,0
8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010,1,-2
56,Leganes,1,35,38,8,11,19,36,55,0,0,0,0,0,0,0,2016,2016,17,-19
58,Condal,1,22,30,7,8,15,37,57,0,0,0,0,0,0,0,1956,1956,16,-20
44,Eibar,3,132,114,35,27,52,139,167,0,0,0,0,0,0,0,2014,2014,10,-28
57,Xerez,1,34,38,8,10,20,38,66,0,0,0,0,0,0,0,2009,2009,20,-28
60,Cultural Leonesa,1,14,30,5,4,21,34,65,0,0,0,0,0,0,0,1955,1955,15,-31
52,Real Union,4,56,72,21,14,37,153,184,0,0,0,0,0,1,1,1929,1931,6,-31

In [19]:
print("Team with highest number of Goal Difference")
Liga.iloc[0,[0,19]].head(3)

Team with highest number of Goal Difference

Team               Real Madrid
Goal_diff_count           2807
Name: 1, dtype: object

In [20]:
print("Team with lowest number of Goal Difference")
Liga.iloc[8,[0,19]].head(3)

Team with lowest number of Goal Difference

Team               Real Sociedad
Goal_diff_count               -2
Name: 8, dtype: object

Q5) Create a new column with name “Winning Percent” and append it to the data set (5 points)

Percentage of Winning = (GamesWon / GamesPlayed)*100

If there are any numerical error, replace it with 0%

Print the top 5 teams which has the highest Winning percentage

In [21]:
Liga["Winning Percent"] = (Liga["GamesWon"] / Liga["GamesPlayed"])*100

In [22]:
Liga = Liga.sort_values(by=["Winning Percent"],ascending=False)

In [23]:
print("The top 5 teams which have the highest Winning percentage are :")
Liga.loc[:,["Team","Winning Percent"]].head(5)

The top 5 teams which have the highest Winning percentage are :

                Team  Winning Percent
Pos
1        Real Madrid        59.630702
2          Barcelona        57.241130
3    Atletico Madrid        47.475134
4           Valencia        44.557057
5    Athletic Bilbao        43.772629

In [24]:
Liga.head(2)

,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,...,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Goal_diff_count,Winning Percent
Pos,,,,,,,,,,,,,,,,,,,,,
1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,...,8,8,3,4,79,1929,1929,1,2807,59.630702
2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,...,12,12,4,6,83,1929,1929,1,2786,57.241130

Q6) Group teams based on their “Best position” and print the sum of their points for all positions (10 points)

Eg: Best Position     Points

         1                   25000

         2                    7000

Ans) Grouping teams as per my understanding as :

"Good Performing Team" (Been Champion or Runner-up more than 4 times)

"Average Performing Team" (Been Third or Fourth more than 4 times)

"Bad Performing Team" (Been Fifth or Sixth more than 4 times) 

Creating a new column as "Team_Performance" per the above conditions.

In [70]:
Liga["Team_Performance"] = np.where((Liga["Champion"] >= 4) & (Liga["Runner-up"] >= 4)  , "Good Performing Team", 
                           np.where((Liga["Third"] >= 4) & (Liga["Fourth"] >= 4), "Medium Performing Team",
                           np.where((Liga["Fifth"] >= 4) & (Liga["Sixth"] >= 4),"Low Performing Team", 
                                    "Performance Not considered")))
Liga.head(10)

,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,...,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Goal_diff_count,Winning Percent,Team_Performance
Pos,,,,,,,,,,,,,,,,,,,,,
1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,...,8,3,4,79,1929,1929,1,2807,59.630702,Good Performing Team
2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,...,12,4,6,83,1929,1929,1,2786,57.241130,Good Performing Team
3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,...,9,7,6,56,1929,2002,1,1225,47.475134,Good Performing Team
4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,...,11,10,7,50,1931,1987,1,929,44.557057,Good Performing Team
5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,...,5,8,10,49,1929,1929,1,931,43.772629,Good Performing Team
21,Villarreal,17,970,646,266,172,208,892,789,0,...,2,3,2,9,1998,2013,2,103,41.176471,Performance Not considered
6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,...,5,12,6,32,1934,2001,1,307,41.112957,Medium Performing Team
8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,...,5,4,3,19,1929,2010,1,-2,37.532580,Performance Not considered
11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,...,1,0,1,12,1941,2014,1,-136,36.797386,Performance Not considered
7,Espanyol,82,2792,2626,948,608,1070,3609,3889,0,...,5,2,5,16,1929,1994,3,-280,36.100533,Medium Performing Team

In [66]:
# Copying the data to 3 categories
Performance_Table = Liga.loc[:,["Team","Team_Performance","Points"]]
GoodPerformance = Performance_Table.loc[Performance_Table["Team_Performance"] == "Good Performing Team"]
MediumPerformance = Performance_Table.loc[Performance_Table["Team_Performance"] == "Medium Performing Team"]
LowPerformance = Performance_Table.loc[Performance_Table["Team_Performance"] == "Low Performing Team"]

In [77]:
print("Sum of Points for the Good Performing teams : ")
GoodPerformance.loc[:,["Points"]].sum()

Sum of Points for the Good Performing teams :

Points    18843
dtype: int64

In [78]:
print("Sum of Points for the Medium Performing teams : ")
MediumPerformance.loc[:,["Points"]].sum()

Sum of Points for the Medium Performing teams :

Points    7720
dtype: int64

In [79]:
print("Sum of Points for the Low Performing teams : ")
LowPerformance.loc[:,["Points"]].sum()

Sum of Points for the Low Performing teams :

Points    3673
dtype: int64